theme = "catppuccin_latte"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
rulers = [100]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "selections"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "version-control", "position"]

[editor.indent-guides]
render = true
character = "â¸½"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false